export function slugify(value: string) {
  return value
    .normalize("NFKC")
    .trim()
    .toLowerCase()
    .replace(/['"]/g, "")
    .replace(/[^\p{Letter}\p{Number}]+/gu, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 96);
}

export function isAutoGeneratedPostSlug(input: {
  slug: string;
  title: string;
  status: "draft" | "scheduled" | "published";
}) {
  if (input.status !== "draft") return false;
  return (
    /^untitled-[0-9a-f]{8}$/i.test(input.slug) ||
    input.slug === slugify(input.title)
  );
}

export function resolvePostSlug(input: {
  currentSlug: string;
  currentTitle: string;
  currentStatus: "draft" | "scheduled" | "published";
  submittedSlug: string;
  nextTitle: string;
}) {
  const submittedSlug = slugify(input.submittedSlug);
  const shouldFollowTitle =
    isAutoGeneratedPostSlug({
      slug: input.currentSlug,
      title: input.currentTitle,
      status: input.currentStatus,
    }) && submittedSlug === input.currentSlug;
  const source = shouldFollowTitle
    ? input.nextTitle
    : input.submittedSlug || input.nextTitle;
  return slugify(source) || input.currentSlug;
}

export function splitTags(value: string | string[]) {
  const source = Array.isArray(value) ? value : value.split(/[,，]/);
  return [...new Set(source.map((tag) => tag.trim()).filter(Boolean))].slice(0, 12);
}

export function normalizeTextLineBreaks(value: string) {
  return value.replace(/\r\n?/g, "\n").replace(/\\n[ \t]*/g, "\n");
}

export function mdxToText(value: string) {
  return value
    .replace(/```[\s\S]*?```/g, " ")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/<[^>]+>/g, " ")
    .replace(/!\[[^\]]*]\([^)]*\)/g, " ")
    .replace(/\[([^\]]+)]\([^)]*\)/g, "$1")
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/[*_~>|-]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export function estimateReadingMinutes(value: string) {
  const plain = mdxToText(value);
  const latinWords = plain.match(/[A-Za-z0-9]+/g)?.length ?? 0;
  const cjkCharacters = plain.match(/[\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}]/gu)
    ?.length ?? 0;
  return Math.max(1, Math.ceil(latinWords / 220 + cjkCharacters / 500));
}

export function parseDateInput(value: FormDataEntryValue | null) {
  if (!value || typeof value !== "string") return null;
  const parsed = new Date(value);
  return Number.isNaN(parsed.valueOf()) ? null : parsed;
}

export function isSafeInternalPath(value: string) {
  return value.startsWith("/") && !value.startsWith("//") && !value.includes("\\");
}

export function buildAuthCallbackUrl(value: string, origin: string) {
  const callbackPath = isSafeInternalPath(value) ? value : "/admin";
  return new URL(callbackPath, origin).toString();
}
