import { describe, expect, it } from "vitest";
import {
  buildAuthCallbackUrl,
  estimateReadingMinutes,
  isAutoGeneratedPostSlug,
  isSafeInternalPath,
  mdxToText,
  normalizeTextLineBreaks,
  resolvePostSlug,
  slugify,
  splitTags,
} from "../app/lib/content-utils";

describe("content utilities", () => {
  it("creates stable unicode slugs", () => {
    expect(slugify("  你好，Docker 世界！ ")).toBe("你好-docker-世界");
    expect(slugify("RelayQR: v2")).toBe("relayqr-v2");
  });

  it("lets untouched draft slugs follow their title", () => {
    expect(
      resolvePostSlug({
        currentSlug: "untitled-a1b2c3d4",
        currentTitle: "没有标题的新纸片",
        currentStatus: "draft",
        submittedSlug: "untitled-a1b2c3d4",
        nextTitle: "第一篇认真写的纸片",
      }),
    ).toBe("第一篇认真写的纸片");

    expect(
      resolvePostSlug({
        currentSlug: "first-note",
        currentTitle: "First Note",
        currentStatus: "draft",
        submittedSlug: "first-note",
        nextTitle: "A Better Note",
      }),
    ).toBe("a-better-note");
  });

  it("keeps manual and published slugs stable", () => {
    expect(
      resolvePostSlug({
        currentSlug: "my-permalink",
        currentTitle: "First Note",
        currentStatus: "draft",
        submittedSlug: "my-permalink",
        nextTitle: "Renamed Note",
      }),
    ).toBe("my-permalink");
    expect(
      resolvePostSlug({
        currentSlug: "first-note",
        currentTitle: "First Note",
        currentStatus: "published",
        submittedSlug: "first-note",
        nextTitle: "Renamed Note",
      }),
    ).toBe("first-note");
  });

  it("recognizes only draft placeholders and title-derived slugs as automatic", () => {
    expect(
      isAutoGeneratedPostSlug({
        slug: "untitled-a1b2c3d4",
        title: "没有标题的新纸片",
        status: "draft",
      }),
    ).toBe(true);
    expect(
      isAutoGeneratedPostSlug({
        slug: "first-note",
        title: "First Note",
        status: "draft",
      }),
    ).toBe(true);
    expect(
      isAutoGeneratedPostSlug({
        slug: "first-note",
        title: "First Note",
        status: "published",
      }),
    ).toBe(false);
  });

  it("deduplicates and trims tags", () => {
    expect(splitTags("Docker, 自托管，Docker,  猫 ")).toEqual([
      "Docker",
      "自托管",
      "猫",
    ]);
  });

  it("normalizes real and escaped line breaks without treating /n as markup", () => {
    expect(normalizeTextLineBreaks("喵喵喵，\\n 这里是 Mazha0309")).toBe(
      "喵喵喵，\n这里是 Mazha0309",
    );
    expect(normalizeTextLineBreaks("第一行\r\n第二行")).toBe("第一行\n第二行");
    expect(normalizeTextLineBreaks("普通的 /n 还是普通文字")).toBe(
      "普通的 /n 还是普通文字",
    );
  });

  it("produces searchable plain text from MDX", () => {
    expect(
      mdxToText("## 标题\n\n[链接](https://example.com) 与 `code`。\n\n<Note>纸条</Note>"),
    ).toBe("标题 链接 与 code。 纸条");
  });

  it("estimates at least one minute", () => {
    expect(estimateReadingMinutes("很短。")).toBe(1);
  });

  it("accepts only local redirect targets", () => {
    expect(isSafeInternalPath("/admin/posts")).toBe(true);
    expect(isSafeInternalPath("//evil.example")).toBe(false);
    expect(isSafeInternalPath("https://evil.example")).toBe(false);
    expect(isSafeInternalPath("/admin\\evil")).toBe(false);
  });

  it("builds same-origin auth callbacks for encoded unicode paths", () => {
    expect(
      buildAuthCallbackUrl(
        "/blog/%E4%B8%80%E5%BC%A0%E6%96%B0%E7%9A%84%E7%BA%B8%E7%89%87",
        "https://mazha0309.top",
      ),
    ).toBe(
      "https://mazha0309.top/blog/%E4%B8%80%E5%BC%A0%E6%96%B0%E7%9A%84%E7%BA%B8%E7%89%87",
    );
    expect(
      buildAuthCallbackUrl("https://evil.example", "https://mazha0309.top"),
    ).toBe("https://mazha0309.top/admin");
  });
});
